### ISSUE TITLE
PID file

### ISSUE THREAD

**Issue by Obarun** [openntpd-portable/openntpd-portable#20]
hello,

i try to use the -p options, but it seem do not working. I use Arch but under runit for init and service management. You can find my pkgbuild here https://github.com/Obarun/obarun-pkgbuild/tree/master/openntpd-nosystemd.

i start the service like this : 

> # !/usr/bin/sh
> 
> if ! [ -d /run/openntpd ]; then
>     mkdir -p -m 0755 /run/openntpd
> fi
> exec 2>&1
> exec /usr/bin/ntpd -s -v -d -p /run/openntpd/ntpd.pid 

Well all work fine appart the pid, it doesn't written on /run/openntpd/ntpd.pid.
this is the output of ps aux | grep ntpd

> root     3837  0.0  0.0   4064   680 ?        Ss   18:22   0:00 runsv ntpd
> root     3838  0.0  0.0   4208   696 ?        S    18:22   0:00 svlogd -tt /var/log/ntpd
> root     3839  0.0  0.0   4480   724 ?        S<   18:22   0:00 ntpd: [priv]
> ntp      3840  0.0  0.0   4832  1404 ?        S<   18:22   0:00 ntpd: ntp engine
> ntp      3841  0.0  0.0   4904   104 ?        S    18:22   0:00 ntpd: dns engine

and a part of the log output

> 2016-03-07_14:48:57.35816 reply from 198.23.200.19: offset 0.001073 delay 0.306139, next query 30s 
> 2016-03-07_14:48:57.37546 reply from 108.61.56.35: offset 0.007901 delay 0.323442, next query 31s 
> 2016-03-07_14:49:27.71332 reply from 198.23.200.19: offset -0.000205 delay 0.307788, next query 30s 
> 2016-03-07_14:49:29.03669 reply from 108.61.56.35: offset 0.009028 delay 0.322818, next query 32s 
> 2016-03-07_14:49:58.34446 reply from 198.23.200.19: offset 0.001120 delay 0.304929, next query 33s 
> 2016-03-07_14:50:00.67599 reply from 108.61.56.35: offset 0.013067 delay 0.329417, next query 33s 
> 2016-03-07_14:50:32.05762 reply from 198.23.200.19: offset 0.023799 delay 0.350934, next query 33s 
> 2016-03-07_14:50:33.38421 reply from 108.61.56.35: offset 0.007890 delay 0.325477, next query 30s 
> 2016-03-07_14:50:33.38423 adjusting local clock by -0.007881s

Certainly i do something wrong, have an idea about this?
thanks

**Comment by Obarun** [comment]
nobody here??

**Comment by busterb** [comment]
Present, just busy. Taking a look now.

**Comment by busterb** [comment]
The problem is you have specified the '-d' flag which says to not daemonize. If you do this, it intentionally does not write the PID file. In other words, '-d' and '-p' are mutually exclusive.

I'm not super familiar with runit, but why do you use '-d' with exec, and the pid file? Why not just do this:

```
#!/usr/bin/sh
if ! [ -d /run/openntpd ]; then
mkdir -p -m 0755 /run/openntpd
fi
/usr/bin/ntpd -s -v -p /run/openntpd/ntpd.pid
```

Either you care about the PID file for some reason (because it daemonized and you want to kill it by PID later), or you want it to run as a foreground normal process, in which case your init system should be able to manage it directly.

I wonder if we really should even keep the PID file patch around anymore. I added it from gentoo's patch list, but it feels like an anachronism with modern inits, or just running 'pkill ntpd' should be sufficient.

**Comment by Obarun** [comment]
exec replaces the shell without creating a new process, this is the normal use for runit. I need to use the -d flag to allow runit to keep the control on it.

Have a pid on file can be useful when you look after it with some other script or applications like webmin for example. Runit do the stuff as you said, pid written on file or not, for me it's just for a ergononmic work :). Obviously it can be found with another method but it's very simple when i have the pid written on file.
Anyway thanks for your explanation

**Comment by busterb** [comment]
Changing it to just write if -p if specified.
