### ISSUE TITLE
 --with-privsep-path not working

### ISSUE THREAD

**Issue by johnwmail** [openntpd-portable/openntpd-portable#6]
I compiled openntpd-5.7p2 on my debian/amd64, it work.
but the "--with-privsep-path" flag not working.

ntp.c use "pw->pw_dir" to chroot rather then PRIVSEP_PATH

sorry for my english

**Comment by busterb** [comment]
The '--with-privsep-path' option does not directly change the path that the binary uses. It changes the instructions that are displayed and what directory is checked when you type 'make install'. This is intentional.

The home directory of the unprivileged user (default '_ntp', but you can change it with --with-privsep-user) is always used by ntpd as the privsep path. If you want to use a different directory and the privsep user already exists, change that user's home directory to the desired path. The directory should be empty, owned by root, and unwritable by all other users. openntpd will never write into this directory.

**Comment by johnwmail** [comment]
OK, it is not a bug, it is intention
