### ISSUE TITLE
Building with OpenSSL instead of LibreSSL

### ISSUE THREAD

**Issue by epsilon-0** [openntpd-portable/openntpd-portable#67]
I am currently trying to build this with TLS contraints but with OpenSSL and so far have not had any luck getting it to build.

It seems to be relying on this part in `configure.ac` :
```
# check for libtls                                                                                                                      
AC_SEARCH_LIBS([tls_config_set_ca_mem],[tls],
               [LIBS="$LIBS -ltls -lssl -lcrypto"],,[-lssl -lcrypto])
AC_CHECK_FUNCS([tls_config_set_ca_mem])

# check if libtls uses 3-argument tls_write                                                                                             
AC_CACHE_CHECK([if tls_write takes 3 arguments], ac_cv_have_tls_write_3_arg, [
        AC_LINK_IFELSE([AC_LANG_PROGRAM([[
#include <tls.h>                                                                                                                        
size_t outlen;
                ]], [[ tls_write(NULL, NULL, 0); ]])],
        [ ac_cv_have_tls_write_3_arg="yes" ],
        [ ac_cv_have_tls_write_3_arg="no"
        ])
])

AC_ARG_ENABLE([https-constraint],
        AS_HELP_STRING([--disable-https-constraint],
                [Disable HTTPS Constraint Functionality]))

AM_CONDITIONAL([HAVE_LIBTLS],
        [test "x$ac_cv_func_tls_config_set_ca_mem" = xyes \
          -a "x$ac_cv_have_tls_write_3_arg" = xyes \
          -a "x$enable_https_constraint" != xno])

if test "x$ac_cv_func_tls_config_set_ca_mem" = xyes \
        -a "x$ac_cv_have_tls_write_3_arg" = xyes \
        -a "x$enable_https_constraint" != xno; then
        AC_DEFINE([HAVE_LIBTLS], [yes])
fi
```

Is there anyway to get OpenNTPD to build with TLS constraints with OpenSSL ?

**Comment by Fincer** [comment]
You may want to check my patchset for OpenNTPD which may be a good start for achieving what you want:

https://github.com/Fincer/openntpd-openssl

It still has some issues on Linux (reading certs mainly) and is not compherensively tested yet. Preliminary testing looks good in general, though.

**Comment by epsilon-0** [comment]
Thanks!

**Comment by Fincer** [comment]
You're welcome! Hopefully it helps you. I also had personal interest and motivation to get OpenSSL support. I decided to take a step forward since this project does not officially support OpenSSL.

In my version of OpenNTPD, you can enable OpenSSL by doing the following:

**1)** Apply [my patches](https://github.com/Fincer/openntpd-openssl/tree/master/patches) into OpenNTPD source code. Patches should be applied after [openntpd-portable](https://github.com/openntpd-portable/openntpd-portable) patchset.
**2)** Compile OpenNTPD with [--with-openssl=yes](https://github.com/Fincer/openntpd-openssl/blob/master/arch/openntpd-git/PKGBUILD#L103) option.
**3)** After successful installation, open `/etc/ntpd.conf`
**4)** set `constraint_engine openssl`
**5)** You may need to turn off CA (Certificate Authority) validation, set `constraint_ca_validation  false`
**6)** Start OpenNTPD (systemd: `openntpd.service`)

Certificate validation issue still bothers me a little bit. Turning it off is not an actual solution but more like a workaround.
